secrets:
    OPENWEATHER_API_KEY: ENC[AES256_GCM,data:Ql/bxpsVEWWDL5mQjCjRWy1hmDRFyZwg6Yh0a9bhThk=,iv:Zn46evCQAeKLnl/ApcazUNQLtBuzmGdjmIDIpP7GFH8=,tag:hUJeg+JtR19CSO+Z8TwibA==,type:str]
    EMAIL_FROM: ENC[AES256_GCM,data:3fQL0tV7MHafjyGtUEzeJtGKKpQyaw==,iv:eCDHOfpR8PNuRYenLQ/Gdo/cZ9cNaUeIb71OrFWYlWk=,tag:kWeMh0nDuOuo7Lvk40ldDw==,type:str]
    EMAIL_TO: ENC[AES256_GCM,data:wtnNJUYRpsJL+03+8uEB7DL7NuOZn8eO,iv:Jwtpqk3Hsl4RWpCxJF3fI3NXxK9rKsUa5VxdFGsd6WY=,tag:zZnrmJhMr+pA1MlxOxcSiA==,type:str]
    EMAIL_PASS: ENC[AES256_GCM,data:lK50TiFUj6Q/b0mEQS+Cvw==,iv:DeKMdXVfqOyBtroUTCb3ZSIsyfIu12DLs7/yD33+M+I=,tag:Ee9HjgGGPn2T42TwjIPM7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RjNXa3c4TTZPU1ZZQS94
            ZHd2ZGNDR3UzaDBxV3JBQUJwS25nUWZVOVdVClhpejVXcUVEK00vYk1peE1RYm9N
            cEdJVWQ1akVjVU50dXBBL1N6eHcrVGsKLS0tIGlreElLcGNWa0pKMGJVUUtWZ1Rt
            Sm85a3NhMzhHVDdWMHRLNVovUm1EQ1EKLph68xMBMA0Wm2gsGBkVzNa5Gfq2Hz0R
            UzudcZJEV+ySoIJqXa5qZAsQCLsODKK+am6scpiCBdbjJEO1Hps+TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1scfdeeyeassgvmey569kn5xwtl47gh3v0gqkuu0ndyhaajdr2a6s6dswul
    lastmodified: "2026-10-03T21:46:02Z"
    mac: ENC[AES256_GCM,data:gHl2vD1GWx83q/9zVEDoqeG+LexSF+SQRHqurLCahWVdnAUmfeVzTy6N7y8FlXeqaB0PwzQc49cnGScXSMF0Db5bjkJGrC+eASYHqe0lLUNfnW0LydnKkIdvrHa16Q8Tf5w6zvrJZiYjQG/TVMvDv+1zsUQPGc+A4g/l57e9PL4=,iv:19q9miTH1jBrSbleI+PIT/0lG6Jfiv3MgEQ3X8Nk6bU=,tag:pd42xksY0EhWTi3m2iIUXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
